KayStrobach:
  Ldap:
    host:
    port:
    admin:
      dn:
      password:
    defaults:
      attributes:
        - givenName
        - sn
        - uidNumber
        - employeeType
        - mail
        - ou